# ZSHRC Configuration

# Specify your defaults in this environment variable
export HOMEBREW_CASK_OPTS="--appdir=/Applications --caskroom=/usr/local/Caskroom"

# AWS Cli completions
# source /usr/local/share/zsh/site-functions/_aws
