# Link bash completions
# brew tap homebrew/version
# brew install bash-completion2
if [ -f $(brew --prefix)/share/bash-completion/bash_completion ]; then
    . $(brew --prefix)/share/bash-completion/bash_completion
fi

# Tab cycles through options
bind 'set show-all-if-ambiguous on'
set completion-ignore-case on
bind 'TAB:menu-complete'

# Prompt
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# Default Homebrew Cask Options
export HOMEBREW_CASK_OPTS="--appdir=/Applications --caskroom=/usr/local/Caskroom"

# AWS Cli completions
# complete -C aws_completer aws

export NVM_DIR="$HOME/.nvm"
. "$(brew --prefix nvm)/nvm.sh"
